FROM golang:1.18.4 AS go

# update together with .github/workflows/ci.yml
FROM golangci/golangci-lint:v1.47.2 AS linter

FROM go AS dev
COPY --from=linter /usr/bin/golangci-lint /usr/bin/
WORKDIR /app
