# This file specifies the exclusions needed for compatibility with older Go versions and dependencies.
# It is merged with the main .golangci.yml file to run the linter using the latest dependencies and go.mod.
linters:
  exclusions:
    rules:
      # patch for latest deps
      - text: 'for loop can be changed to use an integer range' # remove after go 1.22+
        linters:
          - intrange
      - text: 'context.Background\(\) could be replaced by t.Context\(\) in TestExecutor' # remove after go 1.24+
        linters:
          - usetesting
